### PR TITLE
Changed CI to deploy only on tags

### PR DESCRIPTION
**Pull request by barambani**

### CODE REVIEW

**Comment by fiadliel** [comment]
My 2c: this is better than the current situation.

But in the longer term, it's quite fine to publish artifacts on each merge, as long as the non-tagged releases go into a snapshots repository instead of releases.

**Comment by barambani** [comment]
Very true. While I'm here I'll give it a try in this PR. Thanks 👍

**Comment by barambani** [comment]
I couldn't find a good way to release snapshots with `sbt-release-early`. Looking into the code it looks like that they rely on the sonatype plugin and the latter depends on the `-SNAPSHOT` suffix to identify non-final versions. This suffix is exactly one of the things that `sbt-release-early` is trying to obsolete ([see here](https://github.com/scalacenter/sbt-release-early/wiki/Essential%3A-Installation#why-not-regular--snapshots)). 
So, I'm waiting for some feedback anyway, in case there is a possibility that I didn't find, but in the meantime I wound't stop this. 
@sirocchj , what do you think ?

**Comment by sirocchj** [comment]
First things first: thanks a mil!! Wanted to do this for a while and kept on forgetting to do it when I had a chance!

I’m more than happy with this change and yes, releasing -SNAPSHOT (on snapshot repo) is against release early philosophy (which is about pretty much releasing every change on master that passes CI).

Although in principle I like the idea, I’m even more comfortable with explicitly releasing only when a tag is created. We’re still delegating all the heavy lifting to the CI (contrary to sbt-release normal paradigm of execution) so it’s a big +1 from me, but I’m more than happy to be told of better ways!

**Comment by fiadliel** [comment]
I don't like sbt-release either.

I usually use sbt-git for versioning, which sets `isSnapshot` to true if not exactly at a tag. It also sets the version based on the current commit, `-SNAPSHOT` is evil, and not generally required for snapshot repos.

**Comment by barambani** [comment]
Thanks @fiadliel ,I've explored that possibility as well, but I didn't find any way to force `sbt-release-early` to publish to a snapshot destination as it uses `sonatypeRelease` ([see here](https://github.com/scalacenter/sbt-release-early/blob/d5a820af6c678e6961c7d77f7cecfbb972d4d97a/src/main/scala/ch/epfl/scala/sbt/release/ReleaseEarlyPlugin.scala#L266)), that, AFAICT uses `-SNAPSHOT` to pick a destination.
I've tried to open the discussion with Scala Center anyway, so let's see how it goes. In the meantime I can merge this.

**Comment by fiadliel** [comment]
Just as a reply about that - I think sonatype uses `isSnapshot` - you should be able to say `isSnapshot := true`.
I guess I can try doing a PR 😄

**Comment by barambani** [comment]
Thanks. Then I will try as you suggest. I would ask you to review it though 😄. Thanks again.

**Pull request merged**
